import type { Metadata } from "next";
import "./globals.css";
import HomeHeader from "@/components/HomeHeader";
import Footer from "@/components/Footer";
import { Great_Vibes } from "next/font/google";
import { Inter } from "next/font/google";


const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400"
});

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "UIUX Hackathon",
  description: "Generated by create next app",
};

export default function othersLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <div className="max-w-screen-2xl mx-auto">
          
        
        <HomeHeader/>
        {children}
        <Footer/>
        </div>
        
  );
}
